# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "/"
    weight: 10
  - name: Research
    url: research
    weight: 20
  - name: People
    weight: 30
  - name: Members
    url: people
    parent: People
    weight: 1
  - name: Alumni
    url: alumni
    parent: People
    weight: 2
  - name: Open Positions
    url: position
    parent: People
    weight: 3
  - name: Publications
    url: publication
    weight: 40
  - name: Resources
    weight: 50
  - name: Lectures and Tutorials
    url: blog
    parent: Resources
    weight: 1
  - name: Software
    url: software
    parent: Resources
    weight: 2
  - name: News
    url: news
    weight: 60
  - name: Contact
    url: contact
    weight: 80
