[book]
title = "Density Functional Theory"
authors = ["Rudra Banerjee"]
language = "en"

[output.html]
mathjax-support = false
theme = "theme"
additional-css = ["src/custom.css"]
additional-js = ["src/custom.js"]
site-url = "/dft-notes/"
